# Generated by Django 3.2.1 on 2024-06-18 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samess_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='receiver',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.CharField(max_length=20),
        ),
    ]
