# Generated by Django 3.2.1 on 2024-06-19 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samess_api', '0002_auto_20240618_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='iv',
            field=models.CharField(default='iv', max_length=500),
        ),
    ]
